package telas;

import ferramentas.Globais;
import java.awt.Color;

/**
 *
 * @author jonasdhein
 */
public class TelaProgresso extends javax.swing.JFrame {

    /**
     * Creates new form TelaProgresso
     */
    public TelaProgresso() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        prbProgresso = new javax.swing.JProgressBar();
        btnAvancar10 = new javax.swing.JButton();
        btnAvancarRandom = new javax.swing.JButton();
        btnZerar = new javax.swing.JButton();
        btnMaximo = new javax.swing.JButton();
        btnDescontarRandom = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        prbProgresso.setToolTipText("");
        prbProgresso.setStringPainted(true);

        btnAvancar10.setText("+ 10");
        btnAvancar10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvancar10ActionPerformed(evt);
            }
        });

        btnAvancarRandom.setText("Random");
        btnAvancarRandom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvancarRandomActionPerformed(evt);
            }
        });

        btnZerar.setText("Zerar");
        btnZerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZerarActionPerformed(evt);
            }
        });

        btnMaximo.setText("Máx");
        btnMaximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMaximoActionPerformed(evt);
            }
        });

        btnDescontarRandom.setText("- Random");
        btnDescontarRandom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDescontarRandomActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(prbProgresso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAvancar10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAvancarRandom)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnZerar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnMaximo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDescontarRandom)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(prbProgresso, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAvancar10)
                    .addComponent(btnAvancarRandom)
                    .addComponent(btnZerar)
                    .addComponent(btnMaximo)
                    .addComponent(btnDescontarRandom))
                .addContainerGap(162, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAvancar10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvancar10ActionPerformed
        prbProgresso.setValue( prbProgresso.getValue() + 10 );
    }//GEN-LAST:event_btnAvancar10ActionPerformed

    private void btnZerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZerarActionPerformed
        prbProgresso.setValue( prbProgresso.getMinimum() );
    }//GEN-LAST:event_btnZerarActionPerformed

    private void btnAvancarRandomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvancarRandomActionPerformed
        int num_aleatorio = Globais.gerarNumero(20);
        
        prbProgresso.setValue( prbProgresso.getValue() + num_aleatorio );
    }//GEN-LAST:event_btnAvancarRandomActionPerformed

    private void btnMaximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMaximoActionPerformed
        prbProgresso.setValue( prbProgresso.getMaximum() );
    }//GEN-LAST:event_btnMaximoActionPerformed

    private void btnDescontarRandomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDescontarRandomActionPerformed
        int num_aleatorio = Globais.gerarNumero(20);

        prbProgresso.setValue( prbProgresso.getValue() - num_aleatorio );
    }//GEN-LAST:event_btnDescontarRandomActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaProgresso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaProgresso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaProgresso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaProgresso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaProgresso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAvancar10;
    private javax.swing.JButton btnAvancarRandom;
    private javax.swing.JButton btnDescontarRandom;
    private javax.swing.JButton btnMaximo;
    private javax.swing.JButton btnZerar;
    private javax.swing.JProgressBar prbProgresso;
    // End of variables declaration//GEN-END:variables
}
