package aula10;

import ferramentas.Arquivo;
import java.util.ArrayList;
import javax.swing.JFrame;
import modelos.ContaBanco;

/**
 *
 * @author jonasdhein
 */
public class TelaMenu extends javax.swing.JFrame {

    protected static ContaBanco objContaBanco;
    protected static ArrayList<ContaBanco> arrContas;
    
    /**
     * Creates new form TelaMenu
     */
    public TelaMenu() {
        initComponents();
        
        //this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menOperacoes = new javax.swing.JMenuItem();
        jmnSair = new javax.swing.JMenu();
        menSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/banner.png"))); // NOI18N
        jLabel1.setBounds(new java.awt.Rectangle(0, 0, 42, 17));

        jMenu1.setText("Menu");

        menOperacoes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/add.png"))); // NOI18N
        menOperacoes.setText("Operações");
        menOperacoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menOperacoesActionPerformed(evt);
            }
        });
        jMenu1.add(menOperacoes);

        jMenuBar1.add(jMenu1);

        jmnSair.setText("Sair");

        menSair.setText("Sair");
        menSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menSairActionPerformed(evt);
            }
        });
        jmnSair.add(menSair);

        jMenuBar1.add(jmnSair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menSairActionPerformed
        try{
            
            //atualizar o arquivo de CONTAS.txt
            Arquivo objArquivo = new Arquivo("contas.txt");
            boolean retorno = objArquivo.abrirEscrita();
            String linha;
            
            if(retorno){
                for (ContaBanco item : arrContas) {
                    
                    linha = item.getAgencia() + ";" +
                            item.getConta() + ";" +
                            item.getTitular() + ";" +
                            item.getSaldo() + ";" +
                            item.getChequeEspecial() + ";" +
                            item.getChavePix() + ";" + 
                            item.getSenha();
                    
                    objArquivo.escreverLinha(linha);
                }
                objArquivo.fecharArquivo();
            }
            
            System.exit(0);
            
        }catch(Exception ex){
            System.out.println("ERRO AO SAIR: " + ex.getMessage());
        }
    }//GEN-LAST:event_menSairActionPerformed

    private void menOperacoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menOperacoesActionPerformed
            TelaOperacoes tela = new TelaOperacoes();
            tela.setVisible(true); //coloca como visível        
    }//GEN-LAST:event_menOperacoesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jmnSair;
    private javax.swing.JMenuItem menOperacoes;
    private javax.swing.JMenuItem menSair;
    // End of variables declaration//GEN-END:variables
}
